// CENTRALIZED ERROR CODES

export const ErrorCode = {
  // Auth
  AUTH_NO_TOKEN:             "AUTH_NO_TOKEN",
  AUTH_TOKEN_MALFORMED:      "AUTH_TOKEN_MALFORMED",
  AUTH_TOKEN_EXPIRED:        "AUTH_TOKEN_EXPIRED",
  AUTH_TOKEN_INVALID:        "AUTH_TOKEN_INVALID",
  AUTH_TOKEN_REVOKED:        "AUTH_TOKEN_REVOKED",
  AUTH_REFRESH_INVALID:      "AUTH_REFRESH_INVALID",
  AUTH_INVALID_CREDENTIALS:  "AUTH_INVALID_CREDENTIALS",
  AUTH_ACCOUNT_INACTIVE:     "AUTH_ACCOUNT_INACTIVE",

  // Validation
  VALIDATION_FAILED:         "VALIDATION_FAILED",

  // Resource
  RESOURCE_NOT_FOUND:        "RESOURCE_NOT_FOUND",
  RESOURCE_CONFLICT:         "RESOURCE_CONFLICT",
  RESOURCE_LIMIT_REACHED:    "RESOURCE_LIMIT_REACHED",

  // Authorization
  FORBIDDEN_PERMISSION:      "FORBIDDEN_PERMISSION",
  FORBIDDEN_BRANCH_ACCESS:   "FORBIDDEN_BRANCH_ACCESS",

  // Onboarding / Profile Completion
  // SOFT: grace period — informational, never blocks (Days 1–7)
  // HARD: restricted phase — feature blocked until profile complete (Day 8+)
  PROFILE_INCOMPLETE_SOFT:   "PROFILE_INCOMPLETE_SOFT",
  PROFILE_INCOMPLETE_HARD:   "PROFILE_INCOMPLETE_HARD",

  // System
  SYSTEM_RATE_LIMITED:       "SYSTEM_RATE_LIMITED",
  SYSTEM_INTERNAL_ERROR:     "SYSTEM_INTERNAL_ERROR",
} as const;

export type ErrorCodeType = typeof ErrorCode[keyof typeof ErrorCode];