/**
 * Comprehensive, structured catalog of Degrees, Streams, and Specializations
 * categorized professionally for Undergraduate (UG) and Postgraduate (PG) education.
 */

export interface EducationStreamCategory {
  category: string;
  degrees: string[];
}

export const UNDERGRADUATE_CATALOG: EducationStreamCategory[] = [
  {
    category: "Engineering & Technology (B.Tech / B.E. / B.Sc Tech)",
    degrees: [
      "Computer Science and Engineering (CSE)",
      "Information Technology (IT)",
      "Electronics and Communication Engineering (ECE)",
      "Electrical Engineering (EE)",
      "Electrical and Electronics Engineering (EEE)",
      "Mechanical Engineering",
      "Civil Engineering",
      "Chemical Engineering",
      "Aerospace / Aeronautical Engineering",
      "Automobile Engineering",
      "Biomedical Engineering",
      "Biotechnology Engineering",
      "Industrial Engineering",
      "Production Engineering",
      "Mining Engineering",
      "Metallurgical Engineering",
      "Petroleum Engineering",
      "Textile Engineering",
      "Agricultural Engineering",
      "Marine Engineering",
      "Instrumentation Engineering",
      "Robotics Engineering",
      "Artificial Intelligence & Machine Learning",
      "Data Science Engineering",
      "Cyber Security Engineering",
      "Environmental Engineering",
      "Dairy Technology",
      "Food Technology",
      "Polymer Engineering",
      "Ceramic Engineering",
      "Structural Engineering",
      "Nanotechnology",
      "Other Engineering / Technology",
    ],
  },
  {
    category: "Medical & Health Sciences",
    degrees: [
      "MBBS (Bachelor of Medicine and Bachelor of Surgery)",
      "BDS (Bachelor of Dental Surgery)",
      "BAMS (Bachelor of Ayurvedic Medicine and Surgery)",
      "BHMS (Bachelor of Homeopathic Medicine and Surgery)",
      "BUMS (Bachelor of Unani Medicine and Surgery)",
      "BSMS (Bachelor of Siddha Medicine and Surgery)",
      "BPT (Bachelor of Physiotherapy)",
      "BOT (Bachelor of Occupational Therapy)",
      "B.Sc Nursing",
      "B.Pharm (Bachelor of Pharmacy)",
      "BVSc & AH (Veterinary Science and Animal Husbandry)",
      "B.Sc Medical Laboratory Technology (MLT)",
      "B.Sc Radiology / Radiography",
      "B.Sc Optometry",
      "B.Sc Anesthesia Technology",
      "B.Sc Cardiac Care Technology",
      "B.Sc Dialysis Technology",
      "B.Sc Operation Theatre Technology",
      "BASLP (Audiology and Speech-Language Pathology)",
      "B.Sc Nutrition and Dietetics",
      "BNYS (Naturopathy and Yogic Sciences)",
      "Other Medical & Allied Health",
    ],
  },
  {
    category: "Commerce, Business & Management",
    degrees: [
      "B.Com (Bachelor of Commerce) – General",
      "B.Com (Honours)",
      "B.Com in Accounting and Finance",
      "B.Com in Banking and Insurance",
      "B.Com in Taxation",
      "B.Com in E-Commerce",
      "B.Com in Computer Applications",
      "B.Com LLB (Integrated 5-Year)",
      "BBA (Bachelor of Business Administration)",
      "BBA LLB (Integrated 5-Year)",
      "BMS (Bachelor of Management Studies)",
      "BFIA (Bachelor of Finance and Investment Analysis)",
      "CA (Chartered Accountant - Intermediate/Final)",
      "CS (Company Secretary)",
      "CMA (Cost & Management Accountant)",
      "Other Commerce / Management",
    ],
  },
  {
    category: "Arts, Humanities & Social Sciences",
    degrees: [
      "BA General",
      "BA (Honours) in English",
      "BA (Honours) in Hindi / Regional Languages",
      "BA (Honours) in History",
      "BA (Honours) in Political Science",
      "BA (Honours) in Sociology",
      "BA (Honours) in Psychology",
      "BA (Honours) in Economics",
      "BA (Honours) in Philosophy",
      "BA (Honours) in Geography",
      "BA (Honours) in Public Administration",
      "BA (Honours) in Journalism and Mass Communication",
      "BA (Honours) in Anthropology",
      "BA (Honours) in Archaeology",
      "BA (Honours) in Fine Arts",
      "BA (Honours) in Music",
      "BA (Honours) in Theatre / Drama",
      "BA (Honours) in Linguistics",
      "BA (Honours) in Sanskrit",
      "BA (Honours) in Foreign Languages",
      "BSW (Bachelor of Social Work)",
      "BFA (Bachelor of Fine Arts)",
      "BPA (Bachelor of Performing Arts)",
      "BJMC (Bachelor of Journalism and Mass Communication)",
      "BA LLB (Integrated Law 5-Year)",
      "Other Arts & Humanities",
    ],
  },
  {
    category: "Science & Computer Applications",
    degrees: [
      "B.Sc General",
      "B.Sc (Honours) in Physics",
      "B.Sc (Honours) in Chemistry",
      "B.Sc (Honours) in Mathematics",
      "B.Sc (Honours) in Zoology",
      "B.Sc (Honours) in Botany",
      "B.Sc (Honours) in Biology",
      "B.Sc (Honours) in Biotechnology",
      "B.Sc (Honours) in Microbiology",
      "B.Sc (Honours) in Biochemistry",
      "B.Sc (Honours) in Computer Science",
      "B.Sc (Honours) in Statistics",
      "B.Sc (Honours) in Environmental Science",
      "B.Sc (Honours) in Genetics",
      "B.Sc (Honours) in Forensic Science",
      "B.Sc (Honours) in Geology",
      "B.Sc (Honours) in Home Science",
      "B.Sc (Honours) in Agriculture",
      "B.Sc (Honours) in Food Science and Technology",
      "B.Sc (Honours) in Nautical Science",
      "B.Sc (Honours) in Electronics",
      "B.Sc (IT) – Information Technology",
      "BCA (Bachelor of Computer Applications)",
      "B.Sc Horticulture",
      "B.Sc Forestry",
      "Other Science Degree",
    ],
  },
  {
    category: "Law",
    degrees: [
      "LLB (3-Year Degree)",
      "BA LLB (5-Year Integrated)",
      "BBA LLB (5-Year Integrated)",
      "B.Com LLB (5-Year Integrated)",
      "B.Sc LLB (5-Year Integrated)",
      "BSW LLB (5-Year Integrated)",
      "Other Law Degree",
    ],
  },
  {
    category: "Architecture, Planning & Design",
    degrees: [
      "B.Arch (Bachelor of Architecture)",
      "B.Planning (Bachelor of Planning)",
      "B.Des (Fashion Design)",
      "B.Des (Interior Design)",
      "B.Des (Product Design)",
      "B.Des (Communication / Graphic Design)",
      "B.Des (Textile Design)",
      "B.Des (Industrial Design)",
      "B.Des (Game Design)",
      "BFAD (Bachelor of Fashion and Apparel Design)",
      "Bachelor of Interior Design",
      "Other Architecture & Design",
    ],
  },
  {
    category: "Education & Physical Education",
    degrees: [
      "B.Ed (Bachelor of Education)",
      "BA B.Ed / B.Sc B.Ed (Integrated 4-Year)",
      "BPEd (Bachelor of Physical Education)",
      "B.El.Ed (Bachelor of Elementary Education)",
      "Other Education Degree",
    ],
  },
  {
    category: "Hospitality, Tourism & Aviation",
    degrees: [
      "BHM (Bachelor of Hotel Management)",
      "BHMCT (Hotel Management and Catering Technology)",
      "B.Sc in Hospitality and Hotel Administration",
      "BTTM (Bachelor of Tourism and Travel Management)",
      "B.Sc Aviation",
      "BBA in Aviation / Airline Management",
      "Other Hospitality / Tourism",
    ],
  },
  {
    category: "Media, Animation & Mass Communication",
    degrees: [
      "BJMC (Journalism and Mass Communication)",
      "B.Sc in Animation and Multimedia",
      "BAMC (Bachelor of Animation and Multimedia Communication)",
      "B.Sc Visual Communication",
      "BA in Film Making / Direction",
      "Other Media & Communication",
    ],
  },
  {
    category: "Vocational & Other Professional Courses",
    degrees: [
      "B.Voc (Bachelor of Vocation - IT / Retail / Healthcare)",
      "BLIS (Bachelor of Library and Information Science)",
      "BFD (Bachelor of Fashion Designing)",
      "BFT (Bachelor of Fashion Technology)",
      "Bachelor of Fisheries Science",
      "Other Undergraduate Degree",
    ],
  },
];

export const POSTGRADUATE_CATALOG: EducationStreamCategory[] = [
  {
    category: "Engineering & Technology (M.Tech / M.E. / M.S.)",
    degrees: [
      "M.Tech / M.E. Computer Science and Engineering",
      "M.Tech / M.E. Information Technology",
      "M.Tech / M.E. Electronics and Communication Engineering",
      "M.Tech / M.E. Electrical Engineering",
      "M.Tech / M.E. Power Systems Engineering",
      "M.Tech / M.E. Mechanical Engineering",
      "M.Tech / M.E. Thermal Engineering",
      "M.Tech / M.E. Civil Engineering",
      "M.Tech / M.E. Structural Engineering",
      "M.Tech / M.E. Chemical Engineering",
      "M.Tech / M.E. Aerospace Engineering",
      "M.Tech / M.E. Biomedical Engineering",
      "M.Tech / M.E. Biotechnology",
      "M.Tech / M.E. Industrial Engineering",
      "M.Tech / M.E. Production Engineering",
      "M.Tech / M.E. Mining Engineering",
      "M.Tech / M.E. Metallurgical Engineering",
      "M.Tech / M.E. Petroleum Engineering",
      "M.Tech / M.E. Textile Engineering",
      "M.Tech / M.E. Agricultural Engineering",
      "M.Tech / M.E. Instrumentation Engineering",
      "M.Tech / M.E. Robotics and Automation",
      "M.Tech / M.E. Artificial Intelligence & Machine Learning",
      "M.Tech / M.E. Data Science",
      "M.Tech / M.E. Cyber Security",
      "M.Tech / M.E. Environmental Engineering",
      "M.Tech / M.E. VLSI Design",
      "M.Tech / M.E. Nanotechnology",
      "M.Tech / M.E. Software Engineering",
      "M.Tech / M.E. Embedded Systems",
      "M.S. (by Research - Engineering & Tech)",
      "MBA in Technology Management",
      "Other M.Tech / M.E. Specialization",
    ],
  },
  {
    category: "Medical & Health Sciences (MD / MS / MDS / Super-Specialization)",
    degrees: [
      "MD (General Medicine)",
      "MD (Pediatrics)",
      "MD (Dermatology)",
      "MD (Psychiatry)",
      "MD (Radiology / Radiodiagnosis)",
      "MD (Anesthesiology)",
      "MD (Pathology)",
      "MD (Microbiology)",
      "MD (Biochemistry)",
      "MD (Community Medicine / PSM)",
      "MD (Forensic Medicine)",
      "MD (Pharmacology)",
      "MD (Physiology / Anatomy)",
      "MS (General Surgery)",
      "MS (Orthopedics)",
      "MS (ENT / Otorhinolaryngology)",
      "MS (Ophthalmology)",
      "MS (Obstetrics & Gynecology)",
      "MDS (Master of Dental Surgery)",
      "MD (Ayurveda)",
      "MD (Homeopathy)",
      "MD (Unani)",
      "MS / MD (Siddha)",
      "MPT (Master of Physiotherapy - Ortho / Neuro / Sports)",
      "M.Sc Nursing",
      "M.Pharm (Pharmaceutics / Pharmacology / Chemistry)",
      "MVSc (Master of Veterinary Science)",
      "M.Sc Medical Laboratory Technology",
      "M.Sc Radiology",
      "M.Sc Optometry",
      "M.Sc Nutrition and Dietetics",
      "MPH (Master of Public Health)",
      "DM (Super-Specialization: Cardiology / Neurology / Nephrology / Gastro / Endo)",
      "M.Ch (Super-Specialization Surgery: Neurosurgery / CTVS / Urology / Plastic)",
      "Other Postgraduate Medical / Health",
    ],
  },
  {
    category: "Commerce, Management & Business (MBA / M.Com / PGDM)",
    degrees: [
      "MBA (Finance)",
      "MBA (Marketing)",
      "MBA (Human Resource Management / HR)",
      "MBA (Operations & Supply Chain)",
      "MBA (Information Technology / Systems)",
      "MBA (International Business)",
      "MBA (Business Analytics / Data Analytics)",
      "MBA (Healthcare / Hospital Management)",
      "MBA (Rural Management / Agribusiness)",
      "MBA (Entrepreneurship & Innovation)",
      "PGDM (Post Graduate Diploma in Management)",
      "M.Com General",
      "M.Com Accounting and Finance",
      "M.Com Banking and Insurance",
      "M.Com Business Administration",
      "M.Com Applied Economics",
      "MFC (Master of Finance and Control)",
      "MIB (Master of International Business)",
      "Executive MBA (EMBA)",
      "Other Post Graduate Management / Commerce",
    ],
  },
  {
    category: "Arts, Humanities & Social Sciences (MA / MSW / MFA)",
    degrees: [
      "MA English",
      "MA Hindi / Regional Languages",
      "MA History",
      "MA Political Science",
      "MA Sociology",
      "MA Psychology / Clinical Psychology",
      "MA Economics",
      "MA Philosophy",
      "MA Geography",
      "MA Public Administration",
      "MA Journalism and Mass Communication",
      "MA Anthropology",
      "MA Archaeology",
      "MA Fine Arts",
      "MA Music",
      "MA Theatre / Drama",
      "MA Linguistics",
      "MA Sanskrit",
      "MA Foreign Languages",
      "MA Development Studies",
      "MA International Relations",
      "MA Women's Studies",
      "MA Human Rights",
      "MSW (Master of Social Work)",
      "MFA (Master of Fine Arts)",
      "MPA (Master of Performing Arts)",
      "MJMC (Master of Journalism and Mass Communication)",
      "Other MA / Humanities",
    ],
  },
  {
    category: "Science, IT & Computer Applications (M.Sc / MCA / M.Sc IT)",
    degrees: [
      "M.Sc Physics",
      "M.Sc Chemistry",
      "M.Sc Mathematics",
      "M.Sc Zoology",
      "M.Sc Botany",
      "M.Sc Biology",
      "M.Sc Biotechnology",
      "M.Sc Microbiology",
      "M.Sc Biochemistry",
      "M.Sc Computer Science",
      "M.Sc Statistics",
      "M.Sc Environmental Science",
      "M.Sc Genetics",
      "M.Sc Forensic Science",
      "M.Sc Geology",
      "M.Sc Home Science",
      "M.Sc Agriculture",
      "M.Sc Food Science and Technology",
      "M.Sc Nautical Science",
      "M.Sc Electronics",
      "M.Sc Data Science / Artificial Intelligence",
      "M.Sc Actuarial Science",
      "M.Sc Applied Mathematics",
      "M.Sc Bioinformatics",
      "M.Sc Nanoscience",
      "M.Sc Astrophysics",
      "M.Sc Oceanography",
      "M.Sc Geoinformatics",
      "M.Sc (IT) – Information Technology",
      "MCA (Master of Computer Applications)",
      "M.Sc Horticulture",
      "M.Sc Forestry",
      "Other M.Sc Specialization",
    ],
  },
  {
    category: "Law (LLM)",
    degrees: [
      "LLM (Constitutional Law)",
      "LLM (Criminal Law)",
      "LLM (Corporate & Commercial Law)",
      "LLM (International Law)",
      "LLM (Human Rights Law)",
      "LLM (Intellectual Property Rights - IPR)",
      "LLM (Environmental Law)",
      "LLM (Labour & Industrial Law)",
      "LLM (Cyber Law & Data Privacy)",
      "LLM (Taxation Law)",
      "Other LLM Specialization",
    ],
  },
  {
    category: "Architecture, Planning & Design (M.Arch / M.Des / M.Planning)",
    degrees: [
      "M.Arch (Urban Design)",
      "M.Arch (Landscape Architecture)",
      "M.Arch (Building Engineering & Management)",
      "M.Arch (Sustainable / Environmental Architecture)",
      "M.Planning (Urban Planning)",
      "M.Planning (Regional Planning)",
      "M.Planning (Environmental Planning)",
      "M.Planning (Transport Planning)",
      "M.Planning (Housing)",
      "M.Des (Industrial Design)",
      "M.Des (Communication / Graphic Design)",
      "M.Des (Fashion & Textile Design)",
      "M.Des (UX / UI & Interaction Design)",
      "Master of Interior Design",
      "Other Post Graduate Design / Architecture",
    ],
  },
  {
    category: "Education & Physical Education (M.Ed / MPEd)",
    degrees: [
      "M.Ed (Master of Education)",
      "MPEd (Master of Physical Education)",
      "M.El.Ed (Master of Elementary Education)",
      "Other Postgraduate Education",
    ],
  },
  {
    category: "Hospitality, Tourism & Aviation (MHM / MTTM)",
    degrees: [
      "MHM (Master of Hotel Management)",
      "M.Sc Hospitality Administration",
      "MTTM (Master of Tourism and Travel Management)",
      "MBA in Aviation Management",
      "Other Hospitality / Tourism",
    ],
  },
  {
    category: "Mass Communication, Media & Film (MJMC / MA Media)",
    degrees: [
      "MJMC (Master of Journalism and Mass Communication)",
      "M.Sc Animation and Multimedia",
      "MA Visual Communication",
      "MA Film Making / Direction / Production",
      "Master of Advertising and Public Relations (MAPR)",
      "Other Media / Journalism",
    ],
  },
  {
    category: "Vocational & Library Science",
    degrees: [
      "M.Voc (Master of Vocation)",
      "MLIS (Master of Library and Information Science)",
      "M.Sc Fashion Designing / Technology",
      "Master of Fisheries Science",
      "Other Post Graduate Degree",
    ],
  },
];

export const DIPLOMA_CATALOG: EducationStreamCategory[] = [
  {
    category: "Engineering & Polytechnic Diplomas",
    degrees: [
      "Diploma in Computer Science & Engineering",
      "Diploma in Information Technology",
      "Diploma in Electronics & Communication",
      "Diploma in Electrical Engineering",
      "Diploma in Mechanical Engineering",
      "Diploma in Civil Engineering",
      "Diploma in Automobile Engineering",
      "Diploma in Chemical Engineering",
      "Diploma in Mining / Metallurgical Engineering",
      "Other Polytechnic Diploma",
    ],
  },
  {
    category: "Paramedical & Allied Health Diplomas",
    degrees: [
      "Diploma in General Nursing & Midwifery (GNM)",
      "Diploma in Pharmacy (D.Pharm)",
      "Diploma in Medical Laboratory Technology (DMLT)",
      "Diploma in Radiography / X-Ray Technology",
      "Diploma in Operation Theatre Technology (DOTT)",
      "Diploma in Ophthalmic Technology",
      "Other Paramedical Diploma",
    ],
  },
  {
    category: "Management, Design & Other Diplomas",
    degrees: [
      "Diploma in Digital Marketing",
      "Diploma in Graphic Design / UI-UX",
      "Diploma in Fashion Designing",
      "Diploma in Hotel Management",
      "Diploma in Business Administration",
      "Diploma in Financial Accounting",
      "Other Professional Diploma",
    ],
  },
];

export const DOCTORATE_CATALOG: EducationStreamCategory[] = [
  {
    category: "Doctorate & Post-Doctoral Programs",
    degrees: [
      "Ph.D. in Engineering & Technology",
      "Ph.D. in Computer Science / Artificial Intelligence",
      "Ph.D. in Management / Business Administration",
      "Ph.D. in Commerce / Economics",
      "Ph.D. in Science (Physics / Chemistry / Math / Bio)",
      "Ph.D. in Arts & Humanities",
      "Ph.D. in Law",
      "Ph.D. in Medical & Health Sciences",
      "Post-Doctoral Fellowship (PDF)",
      "Other Doctorate / Ph.D.",
    ],
  },
];

export interface SchoolBoardOption {
  code: string;
  name: string;
  requiresStateSelection?: boolean;
  description?: string;
}

export const SCHOOL_BOARD_OPTIONS: SchoolBoardOption[] = [
  { code: "CBSE", name: "Central Board of Secondary Education", description: "CBSE - All India National Board" },
  { code: "ICSE", name: "Indian Certificate of Secondary Education (CISCE, Class 10)", description: "ICSE - Class 10 CISCE" },
  { code: "ISC", name: "Indian School Certificate (CISCE, Class 12)", description: "ISC - Class 12 CISCE" },
  { code: "STATE_BOARD", name: "State Board", requiresStateSelection: true, description: "State Education Board (Select your state)" },
  { code: "NIOS", name: "National Institute of Open Schooling", description: "NIOS - Open Schooling National Board" },
  { code: "IB", name: "International Baccalaureate", description: "IB - International Diploma Programme" },
  { code: "IGCSE", name: "Cambridge IGCSE / A-Levels (CAIE)", description: "Cambridge Assessment International Education" },
  { code: "OTHER", name: "Other", description: "Other Board (Enter board name manually)" },
];

export interface StateBoardOption {
  state: string;
  boardName: string;
  boardCode: string;
}

export const INDIAN_STATE_BOARDS: StateBoardOption[] = [
  { state: "Andhra Pradesh", boardName: "Board of Intermediate / Secondary Education AP (BIEAP / BSEAP)", boardCode: "AP_BOARD" },
  { state: "Assam", boardName: "Assam Higher Secondary Education Council / SEBA", boardCode: "ASSAM_BOARD" },
  { state: "Bihar", boardName: "Bihar School Examination Board (BSEB)", boardCode: "BIHAR_BOARD" },
  { state: "Chhattisgarh", boardName: "Chhattisgarh Board of Secondary Education (CGBSE)", boardCode: "CG_BOARD" },
  { state: "Delhi", boardName: "Delhi Board of School Education (DBSE) / Recognized", boardCode: "DELHI_BOARD" },
  { state: "Goa", boardName: "Goa Board of Secondary and Higher Secondary Education (GBSHSE)", boardCode: "GOA_BOARD" },
  { state: "Gujarat", boardName: "Gujarat Secondary and Higher Secondary Education Board (GSHSEB)", boardCode: "GUJARAT_BOARD" },
  { state: "Haryana", boardName: "Board of School Education Haryana (HBSE)", boardCode: "HARYANA_BOARD" },
  { state: "Himachal Pradesh", boardName: "Himachal Pradesh Board of School Education (HPBOSE)", boardCode: "HP_BOARD" },
  { state: "Jammu and Kashmir", boardName: "Jammu and Kashmir State Board of School Education (JKBOSE)", boardCode: "JK_BOARD" },
  { state: "Jharkhand", boardName: "Jharkhand Academic Council (JAC)", boardCode: "JHARKHAND_BOARD" },
  { state: "Karnataka", boardName: "Karnataka School Examination and Assessment Board (KSEAB)", boardCode: "KARNATAKA_BOARD" },
  { state: "Kerala", boardName: "Kerala Board of Public Examinations / DHSE Kerala", boardCode: "KERALA_BOARD" },
  { state: "Madhya Pradesh", boardName: "Madhya Pradesh Board of Secondary Education (MPBSE)", boardCode: "MP_BOARD" },
  { state: "Maharashtra", boardName: "Maharashtra State Board of Secondary and Higher Secondary Education (MSBSHSE)", boardCode: "MAHARASHTRA_BOARD" },
  { state: "Manipur", boardName: "Board of Secondary Education / Council of Higher Secondary Education Manipur", boardCode: "MANIPUR_BOARD" },
  { state: "Meghalaya", boardName: "Meghalaya Board of School Education (MBOSE)", boardCode: "MEGHALAYA_BOARD" },
  { state: "Mizoram", boardName: "Mizoram Board of School Education (MBSE)", boardCode: "MIZORAM_BOARD" },
  { state: "Nagaland", boardName: "Nagaland Board of School Education (NBSE)", boardCode: "NAGALAND_BOARD" },
  { state: "Odisha", boardName: "Council of Higher Secondary Education / Board of Secondary Education Odisha (CHSE / BSE)", boardCode: "ODISHA_BOARD" },
  { state: "Punjab", boardName: "Punjab School Education Board (PSEB)", boardCode: "PUNJAB_BOARD" },
  { state: "Rajasthan", boardName: "Board of Secondary Education Rajasthan (RBSE)", boardCode: "RAJASTHAN_BOARD" },
  { state: "Tamil Nadu", boardName: "Tamil Nadu Directorate of Government Examinations (TNDGE)", boardCode: "TAMILNADU_BOARD" },
  { state: "Telangana", boardName: "Telangana State Board of Intermediate / Secondary Education (TSBIE / BSE)", boardCode: "TELANGANA_BOARD" },
  { state: "Tripura", boardName: "Tripura Board of Secondary Education (TBSE)", boardCode: "TRIPURA_BOARD" },
  { state: "Uttar Pradesh", boardName: "Uttar Pradesh Madhyamik Shiksha Parishad (UPMSP)", boardCode: "UP_BOARD" },
  { state: "Uttarakhand", boardName: "Uttarakhand Board of School Education (UBSE)", boardCode: "UTTARAKHAND_BOARD" },
  { state: "West Bengal", boardName: "West Bengal Board of Secondary / Higher Secondary Education (WBBSE / WBCHSE)", boardCode: "WB_BOARD" },
  { state: "Other State Board", boardName: "Other State Board", boardCode: "OTHER_STATE_BOARD" },
];

/**
 * Returns structured catalog for the given qualification level along with school board options.
 */
export function getEducationCatalogForLevel(qualificationLevel?: string): {
  qualificationLevel: string;
  categories: EducationStreamCategory[];
  allDegrees: string[];
  boardOptions: SchoolBoardOption[];
  stateBoards: StateBoardOption[];
} {
  const normalized = (qualificationLevel || "").toUpperCase().trim();

  let categories: EducationStreamCategory[];

  if (normalized === "UNDER_GRADUATE" || normalized === "GRADUATE" || normalized === "BACHELORS" || normalized === "UG") {
    categories = UNDERGRADUATE_CATALOG;
  } else if (normalized === "POST_GRADUATE" || normalized === "MASTERS" || normalized === "PG") {
    categories = POSTGRADUATE_CATALOG;
  } else if (normalized === "DIPLOMA") {
    categories = DIPLOMA_CATALOG;
  } else if (normalized === "DOCTORATE" || normalized === "PHD") {
    categories = DOCTORATE_CATALOG;
  } else {
    // Default: combine both UG and PG with group tags
    categories = [
      ...UNDERGRADUATE_CATALOG,
      ...POSTGRADUATE_CATALOG,
    ];
  }

  const allDegrees = categories.flatMap((cat) => cat.degrees);

  return {
    qualificationLevel: normalized || "ALL",
    categories,
    allDegrees,
    boardOptions: SCHOOL_BOARD_OPTIONS,
    stateBoards: INDIAN_STATE_BOARDS,
  };
}
